google_analytics: G-BKTC9CNL0Y
paginate: 10
remote_theme: jekyll/minima
timezone: Asia/Tokyo
title: いちろぐ

# https://github.com/jekyll/minima
minima:
  date_format: "%Y-%m-%d"
  skin: auto
  social_links:
    - title: ichiroku11 repository at GitHub
      icon: github
      url: "https://github.com/ichiroku11"
    - title: ichiroku11 at X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/ichiroku11"

plugins:
  # sitemap.xml
  # https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap
